#---------Parte 1 - Creacion---------# 
CREATE DATABASE EJEMPLO_BD; 
USE EJEMPLO_BD; 

-- Se pueden usar indices para mejorar la optimizacion de las consultas y se puede
-- mejorar el enfasis en la optimizacion

CREATE TABLE FIGURAS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FIGURA_ID VARCHAR(6) NOT NULL,
    #(1) pertenece a coleccion (0) no pertenece a coleccion
	FIGURA_COLECCION TINYINT DEFAULT 0,
	FIGURA_NAME VARCHAR(10),
	FIGURA_TIPO TINYINT, 
	CONSTRAINT FIGURAS_PK PRIMARY KEY (ID) 
 ); 
 
 CREATE TABLE FIGURAS_INDICE ( 
	IDX INTEGER NOT NULL AUTO_INCREMENT,
	ID INTEGER NOT NULL, #Idem CUADRADO, CIRCULO, TRIANGULO ID 
	FIGURAX_ID VARCHAR(6) NOT NULL, #Idem FIGURA_ID 
	TIPO TINYINT DEFAULT 0, #Idem FIGURA_TIP 
	COLX_ID INTEGER DEFAULT 0, #Idem ID_COL 
	CONSTRAINT F_INDICE_PK PRIMARY KEY (FIGURAX_ID) 
 ); 
 
 CREATE TABLE FIGURAS_COLECCION ( 
	ID_COLECCION INTEGER NOT NULL AUTO_INCREMENT, 
    FIGURAC_ID varchar(6),
	ID_CUADRADO INTEGER, 
    ID_TRIANGULO INTEGER, 
	ID_CIRCULO INTEGER, 
    CONSTRAINT COLECCION_PK PRIMARY KEY (ID_COLECCION) 
 ); 
 
 CREATE TABLE CUADRADO ( 
	ID_CUADRADO INTEGER NOT NULL AUTO_INCREMENT, 
    LADO FLOAT, 
    CONSTRAINT CUADRADO_PK PRIMARY KEY (ID_CUADRADO) 
); 

CREATE TABLE CIRCULO ( 
	ID_CIRCULO INTEGER NOT NULL AUTO_INCREMENT, 
    RADIUS FLOAT, 
    CONSTRAINT CIRCULO_PK PRIMARY KEY (ID_CIRCULO) 
); 

CREATE TABLE TRIANGULO ( 
	ID_TRIANGULO INTEGER NOT NULL AUTO_INCREMENT, 
    LADO_A FLOAT, 
    LADO_B FLOAT, 
    LADO_C FLOAT, 
    ALTURA FLOAT, 
    CONSTRAINT TRIANGULO_PK PRIMARY KEY (ID_TRIANGULO) 
); 

#---------Parte 2 - Consultas---------# 
#1 Seleccionar informacion de Figuras
SELECT F.ID, F.FIGURA_ID, F.FIGURA_COLECCION, F.FIGURA_NAME, F.FIGURA_TIPO
FROM FIGURAS AS F;

#2 Seleccionar informacion de las figuras cuadrado con algun lado 5 
SELECT F.FIGURA_ID, F.FIGURA_NAME, F.FIGURA_TIPO 
FROM (FIGURAS AS F JOIN FIGURAS_INDICE AS FI ON F.FIGURA_ID=FI.FIGURAX_ID) 
JOIN (CUADRADO AS C) ON (FI.ID=C.ID_CUADRADO AND FI.TIPO=1) 
WHERE C.LADO=5; 

#3 Seleccionar informacion de las figuras referenciadas entre las tablas Figuras, Figuras indice, y alguna de Cuadrado, Circulo, Triangulo
#El join dentro de la subquery puede ir por fuera. En la consulta principal.
SELECT F.ID, F.FIGURA_ID, F.FIGURA_COLECCION, F.FIGURA_NAME, FI.TIPO 
FROM FIGURAS AS F JOIN ( 
	(SELECT FI.FIGURAX_ID, FI.TIPO 
    FROM (FIGURAS_INDICE AS FI JOIN CUADRADO AS C ON FI.ID=C.ID_CUADRADO AND FI.TIPO=1)
    ) 

    UNION ALL(
    SELECT FI.FIGURAX_ID, FI.TIPO
    FROM (FIGURAS_INDICE AS FI JOIN CIRCULO AS CIR ON FI.ID=CIR.ID_CIRCULO AND FI.TIPO=2)
    ) 
    
    UNION ALL(
    SELECT FI.FIGURAX_ID, FI.TIPO
    FROM (FIGURAS_INDICE AS FI JOIN TRIANGULO AS T ON FI.ID=T.ID_TRIANGULO AND FI.TIPO=3) 
    ) 
) AS FI ON F.FIGURA_ID=FI.FIGURAX_ID 
ORDER BY F.ID ASC;

#4 Seleccionar la cantidad de tipos de figuras, de las primeras 100
SELECT F.FIGURA_TIPO, COUNT(*) as cantidad
FROM FIGURAS AS F
WHERE F.ID < 100
GROUP BY F.FIGURA_TIPO;

#5 Devolver la suma total de todos los radios de circulos
SELECT SUM(C.RADIUS) as suma_radios 
FROM CIRCULO AS C;






